name: Node.js CI

on:
  push:
    branches: [ main ]

env:
  FTP_LOCAL_DIR: './out/'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get npm cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Authenticate with GitHub package registry
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GITHUB_TOKEN }}" > ~/.npmrc
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
        npm run export --if-present
        npm run sitemap --if-present
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ${{ env.FTP_LOCAL_DIR }}
        server-dir: ${{ secrets.FTP_SERVER_DIR }}
